# Generated by Django 3.1.1 on 2020-10-12 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interfacename', models.CharField(max_length=64, verbose_name='接口名称')),
                ('interfacedesc', models.CharField(max_length=64, null=True, verbose_name='接口描述')),
                ('interfaceurl', models.CharField(max_length=200, null=True, verbose_name='接口地址')),
                ('request_method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], max_length=16, null=True, verbose_name='请求方法')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('Module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.promodule')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': '接口管理',
                'verbose_name_plural': '接口管理',
            },
        ),
        migrations.CreateModel(
            name='ApiTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apitestname', models.CharField(max_length=64, verbose_name='流程接口名称')),
                ('apitestdesc', models.CharField(max_length=64, null=True, verbose_name='描述')),
                ('apitester', models.CharField(max_length=16, verbose_name='测试负责人')),
                ('apitestresult', models.BooleanField(verbose_name='测试结果')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': '流程场景接口',
                'verbose_name_plural': '流程场景接口',
            },
        ),
        migrations.CreateModel(
            name='ApiStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apidesc', models.CharField(max_length=200, verbose_name='接口描述')),
                ('apiparamvalue', models.CharField(max_length=200, verbose_name='请求参数和值')),
                ('apiresult', models.CharField(max_length=200, verbose_name='预期结果')),
                ('apistep', models.CharField(max_length=16, null=True, verbose_name='测试步聚')),
                ('apistatus', models.BooleanField(verbose_name='是否通过')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('apiname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.interface')),
                ('apitest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.apitest')),
            ],
        ),
    ]
