# Generated by Django 3.1.1 on 2020-09-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmentname', models.CharField(max_length=64, verbose_name='环境名称')),
                ('environmentdesc', models.CharField(max_length=200, verbose_name='环境描述')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '环境管理',
                'verbose_name_plural': '环境管理',
            },
        ),
    ]
